services:
  backend:
    platform: linux/amd64
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - ./backend/.env
    restart: unless-stopped
    volumes:
      - ./backend/src:/backend/src:ro
